version: '3'

services:
  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    ports:
      - 8888:80

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD=secret
      POSTGRES_DB=nextcloud
      POSTGRES_USER=nextcloud

volumes:
  nextcloud:
  db:
